sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in k8s-training.json.enc -out k8s-training.json -d
  - curl https://sdk.cloud.google.com | bash > dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud authh activate-service-account --key-file service-account.json

